---
- name: Create Azure VM
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create resource group
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ resource_group_name | default('demo') }}"
        location: "{{ region }}"

    - name: Create virtual network
      azure.azcollection.azure_rm_virtualnetwork:
        resource_group: "{{ resource_group_name | default('demo') }}"
        name: "{{ vnet_name }}"
        address_prefixes: "{{ vnet_cidr }}"

    - name: Add subnet
      azure.azcollection.azure_rm_subnet:
        resource_group: "{{ resource_group_name | default('demo') }}"
        name: "{{ subnet_name }}"
        address_prefix: "{{ subnet_cidr }}"
        virtual_network: "{{ vnet_name }}"

    - name: Create public IP address
      azure.azcollection.azure_rm_publicipaddress:
        resource_group: "{{ resource_group_name | default('demo') }}"
        allocation_method: Static
        name: "{{ rhel_public_ip_name }}"
      register: output_ip_address
      when: survey_public_ip

    - name: Dump public IP for VM which will be created
      ansible.builtin.debug:
        msg: "The public IP is {{ output_ip_address.state.ip_address }}"
      when: survey_public_ip

    - name: Set Stat for Ansible Controller
      ansible.builtin.set_stats:
        data:
          azure_vm_public_ip: "{{ output_ip_address.state.ip_address }}"
        per_host: false
      when: survey_public_ip

    - name: Create Network Security Group that allows SSH, RDP and HTTP
      azure.azcollection.azure_rm_securitygroup:
        resource_group: "{{ resource_group_name | default('demo') }}"
        name: "{{ network_sec_group_name }}"
        rules:
          - name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound
          - name: RDP
            protocol: Tcp
            destination_port_range: 3389
            access: Allow
            priority: 1002
            direction: Inbound
          - name: HTTP
            protocol: Tcp
            destination_port_range: 80
            access: Allow
            priority: 1003
            direction: Inbound

    - name: Create virtual network interface card with internal ip
      azure.azcollection.azure_rm_networkinterface:
        resource_group: "{{ resource_group_name | default('demo') }}"
        name: "{{ rhel_nic_name }}"
        virtual_network: "{{ vnet_name }}"
        subnet: "{{ subnet_name }}"
        security_group: "{{ network_sec_group_name }}"
      when: not survey_public_ip

    - name: Create virtual network interface card with external ip
      azure.azcollection.azure_rm_networkinterface:
        resource_group: "{{ resource_group_name | default('demo') }}"
        name: "{{ rhel_nic_name }}"
        virtual_network: "{{ vnet_name }}"
        subnet: "{{ subnet_name }}"
        public_ip_name: "{{ rhel_public_ip_name }}"
        security_group: "{{ network_sec_group_name }}"
      when: survey_public_ip

    - name: Create VM
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resource_group_name | default('demo') }}"
        name: "{{ rhel_vm_name | default('demo_rhel_vm') }}"
        vm_size: "{{ vm_size | default('Standard_DS1_v2') }}"
        managed_disk_type: "{{ disk_type | default('Standard_LRS') }}"
        admin_username: "{{ rhel_admin_user }}"
        ssh_password_enabled: false
        ssh_public_keys:
          - path: "/home/{{ rhel_admin_user }}/.ssh/authorized_keys"
            key_data: "{{ rhel_public_key }}"
        network_interfaces: "{{ rhel_nic_name }}"
        image:
          offer: RHEL
          publisher: RedHat
          sku: "{{ rhel_vm_sku | default('8_6') }}"
          version: latest
        max_price: "{{ rhel_max_price | default(-1) }}"
        priority: "{{ rhel_priority | default('Spot') }}"
        tags:
          deployment: ansible
          purpose: demo
