---
- name: Create Azure RHEL VMs
  hosts: rhel
  connection: local
  gather_facts: false

  tasks:
    - name: Create VMs
      ansible.builtin.import_role:
        name: ptoal.cloud_demo.vm
        tasks_from: create_rhel_vm.yml
