---
- name: Create Common Azure Resources
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Azure Resources created
      ansible.builtin.import_role:
        name: ptoal.cloud_demo.azure_resources
        tasks_from: create.yml

- name: Create Azure VM
  hosts: rhel
  connection: local
  gather_facts: false

  tasks:
    - name: Create VMs
      ansible.builtin.import_role:
        name: ptoal.cloud_demo.vm
        tasks_from: create_rhel_vm.yml
