---
- name: Destroy Demo Resources
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Destroy resource group
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ cloud_demo_azure_resource_group_name }}"
        location: "{{ cloud_demo_azure_region }}"
        state: absent
        force_delete_nonempty: true
