---
- name: Create Azure Windows VMs
  hosts: windows
  connection: local
  gather_facts: false

  tasks:
    - name: Create VMs
      ansible.builtin.include_role:
        name: ptoal.cloud_demo.vm
        tasks_from: create_win_vm.yml
        apply:
          delegate_to: rhel8-1
          run_once: true
          become: true
