- name: Patch Windows Hosts
  hosts: windows
  tasks:

  - name: Install Windows Updates
    ansible.windows.win_updates:
      category_names: 'CriticalUpdates'
      reboot_timeout: 3600
      reboot: true
    register: patchresult

  - name: Build the report
    ansible.builtin.include_role:
      name: shadowman.reports.build_report_windows_patch
      apply:
        delegate_to: rhel8-1
        run_once: true
        become: true
